# 图表基本尺寸
figsize: [7, 5]  # 图表大小 [宽, 高]，单位为英寸

# 字体配置（元素细分）
font_config:
  # 标题字体设置
  title:
    size: 13  # 标题字体大小
    weight: bold  # 字体粗细: normal, bold
  
  # X轴标签字体设置
  xlabel:
    size: 11
    weight: normal
  
  # Y轴标签字体设置
  ylabel:
    size: 11
    weight: normal
  
  # 图例字体设置
  legend:
    size: 9
    weight: normal
  
  # 刻度标签字体设置
  ticks:
    size: 9
    weight: normal
  
  # 默认字体设置
  default:
    size: 10
    weight: normal

# 内边距配置
padding_config:
  title: 10  # 标题内边距
  xlabel: 10  # X轴标签内边距
  ylabel: 10  # Y轴标签内边距
  legend: 3   # 图例内边距

# 颜色配置 - 柔和淡雅的色调
color_palette:
  - "#B3CDE3"  # 淡蓝
  - "#FBB4AE"  # 淡粉
  - "#CCEBC5"  # 淡绿
  - "#DECBE4"  # 淡紫
  - "#FED9A6"  # 淡橙
  - "#FFFFCC"  # 淡黄
  - "#E5D8BD"  # 淡棕
  - "#FDDAEC"  # 淡红